### ISSUE TITLE
i keep getting an Error code

### ISSUE THREAD

**Issue by iR00i** [abhishekkrthakur/bert-entity-extraction#3]
hello i am trying to study abhishek's code but keep getting an error, at first i tried to modify the training function and validation function such that the argument for the `_, _, loss = model()` accepts all the parameters explicitly, but that still gave me the same error, please note that the error arises without any modification whatso ever.
here's my [notebook](https://colab.research.google.com/drive/1uq9DWETrPbBmbGpBT6rpRQKYzB68taiG?usp=sharing) (NOTE: it's the exact same code provided):

```
TypeError                                 Traceback (most recent call last)
<ipython-input-34-2952253b6321> in <module>()
     87         optimizer,
     88         device,
---> 89         scheduler
     90     )
     91     test_loss = eval_fn(

5 frames
<ipython-input-26-42378f43f4c8> in train_fn(data_loader, model, optimizer, device, scheduler)
     16 
     17     optimizer.zero_grad()
---> 18     _, _, loss = model(ids = ids, mask=mask, token_type_ids = token_type_ids, target_pos = target_pos, target_tag = target_tag)
     19     loss.backward()
     20     optimizer.step()

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

<ipython-input-27-6b85467d75fd> in forward(self, ids, mask, token_type_ids, target_pos, target_tag)
     39         )
     40 
---> 41         bo_tag = self.bert_drop_1(o1)
     42         bo_pos = self.bert_drop_2(o1)
     43 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/dropout.py in forward(self, input)
     56 
     57     def forward(self, input: Tensor) -> Tensor:
---> 58         return F.dropout(input, self.p, self.training, self.inplace)
     59 
     60 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in dropout(input, p, training, inplace)
    981     return (_VF.dropout_(input, p, training)
    982             if inplace
--> 983             else _VF.dropout(input, p, training))
    984 
    985 

TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str
```

**Comment by iR00i** [comment]
Ok so, i managed to solve this issue, it turns out that the error im getting is due to a version change in the "transformers" library.
i haven't actually managed to pinpoint exactly what causes the error but for the future, people who get this error, make sure you have the **version 2.11.0** of "transformers" installed to avoid any issue.

im going to try and let abhishek know next time he streams to post the versions of the API he's using, to maintain the longevity of future Github repo.

**Comment by liuhh02** [comment]
> i would actually really appreciate it if someone who might know what changed about the library that causes this issue to tell me, i would try to find out but im too much of a noob and barely understand the backend of the API :P

The change is this:

![image](https://user-images.githubusercontent.com/12683995/111607034-d50b2b80-8812-11eb-96f9-3af5a45ab61e.png)
So when you call the model, you have to explicitly set `return_dict=False`. See the pull request [here](https://github.com/abhishekkrthakur/bert-entity-extraction/commit/178ef0ebc16e5250b7dec786fe147225a62505a0) that fixed the issue
